# This code is part of Cqlib.
#
# (C) Copyright China Telecom Quantum Group 2026
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.

"""Exact-physical native fixed-point optimization."""

from __future__ import annotations

from cqlib.circuit import Circuit
from cqlib.device import Device
from .resynthesis import TwoQubitBlockResynthesisConfig

class NativeOptimizationSummary:
    """Exact physical cost summary at one optimizer checkpoint."""

    @property
    def native_two_qubit_ops(self) -> int: ...
    @property
    def native_two_qubit_depth(self) -> int: ...
    @property
    def total_native_depth(self) -> int: ...
    @property
    def native_total_ops(self) -> int: ...
    @property
    def predicted_log_error(self) -> float | None: ...
    @property
    def unavailable_error_count(self) -> int: ...
    @property
    def imputed_error_count(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __copy__(self) -> NativeOptimizationSummary: ...
    def __deepcopy__(self, memo: dict[int, object]) -> NativeOptimizationSummary: ...

class NativeOptimizationResult:
    """Structured result of one native fixed-point run."""

    @property
    def circuit(self) -> Circuit: ...
    @property
    def changed(self) -> bool: ...
    @property
    def rounds(self) -> int: ...
    @property
    def restored_best(self) -> bool: ...
    @property
    def before(self) -> NativeOptimizationSummary: ...
    @property
    def after(self) -> NativeOptimizationSummary: ...
    def __repr__(self) -> str: ...
    def __copy__(self) -> NativeOptimizationResult: ...
    def __deepcopy__(self, memo: dict[int, object]) -> NativeOptimizationResult: ...

class NativeOptimizer:
    """Reusable optimizer for routed, exact-native physical circuits.

    ``max_rounds`` and ``max_stale_rounds`` must be in the inclusive range
    1 through 255 when supplied.
    """

    def __init__(
        self,
        device: Device,
        *,
        enhanced: bool = False,
        resynthesis: TwoQubitBlockResynthesisConfig | None = None,
        max_rounds: int | None = None,
        max_stale_rounds: int | None = None,
    ) -> None: ...
    @property
    def device(self) -> Device: ...
    @property
    def enhanced(self) -> bool: ...
    @property
    def resynthesis(self) -> TwoQubitBlockResynthesisConfig: ...
    @property
    def max_rounds(self) -> int: ...
    @property
    def max_stale_rounds(self) -> int: ...
    def run(self, circuit: Circuit) -> NativeOptimizationResult: ...
    def __repr__(self) -> str: ...
    def __copy__(self) -> NativeOptimizer: ...
    def __deepcopy__(self, memo: dict[int, object]) -> NativeOptimizer: ...

__all__ = [
    "NativeOptimizationSummary",
    "NativeOptimizationResult",
    "NativeOptimizer",
]
