# Copyright China Telecom Quantum Group 2026
# SPDX-License-Identifier: Apache-2.0

from typing_extensions import deprecated
from ...circuit import Parameter, StandardGate

@deprecated("Use StandardGate.H")
def H(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.X")
def X(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.Y")
def Y(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.Z")
def Z(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.S")
def S(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.SDG")
def SD(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.T")
def T(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.TDG")
def TD(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.CX")
def CX(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.CY")
def CY(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.CZ")
def CZ(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.CCX")
def CCX(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.CX")
def CNOT(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.CCX")
def CCNOT(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.SWAP")
def SWAP(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.X2P")
def X2P(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.X2M")
def X2M(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.Y2P")
def Y2P(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.Y2M")
def Y2M(label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.RX")
def RX(theta: float | Parameter, label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.RY")
def RY(theta: float | Parameter, label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.RZ")
def RZ(theta: float | Parameter, label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.CRX")
def CRX(theta: float | Parameter, label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.CRY")
def CRY(theta: float | Parameter, label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.CRZ")
def CRZ(theta: float | Parameter, label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.XY")
def XY(theta: float | Parameter, label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.XY2P")
def XY2P(theta: float | Parameter, label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.XY2M")
def XY2M(theta: float | Parameter, label: str | None = None) -> StandardGate: ...
@deprecated("Use StandardGate.U")
def U(
    theta: float | Parameter,
    phi: float | Parameter,
    lam: float | Parameter,
    label: str | None = None,
) -> StandardGate: ...
@deprecated("Use StandardGate.FSIM")
def FSIM(
    theta: float | Parameter, phi: float | Parameter, label: str | None = None
) -> StandardGate: ...
@deprecated("Use StandardGate.RXY; order is native (theta, phi)")
def RXY(
    theta: float | Parameter, phi: float | Parameter, label: str | None = None
) -> StandardGate: ...
